import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def is_pandigital(num_str):
        return len(num_str) == 9 and set(num_str) == set('123456789')

    max_pandigital = 0

    for i in range(1, 10000):
        concatenated_product = ''
        n = 1
        while len(concatenated_product) < 9:
            concatenated_product += str(i * n)
            n += 1
        if is_pandigital(concatenated_product):
            max_pandigital = max(max_pandigital, int(concatenated_product))

    return max_pandigital

# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
