import json
import time

# START - CODE GENERATED BY GPT
def solution():
    max_pandigital = 0
    for i in range(1, 10000):
        concatenated_product = ""
        n = 1
        while len(concatenated_product) < 9:
            concatenated_product += str(i * n)
            n += 1
        if len(concatenated_product) == 9 and len(set(concatenated_product)) == 9 and "0" not in concatenated_product:
            pandigital = int(concatenated_product)
            if pandigital > max_pandigital:
                max_pandigital = pandigital
    return max_pandigital
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))