import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def has_same_digits(x, y):
        return sorted(str(x)) == sorted(str(y))

    x = 1
    while True:
        if all(has_same_digits(x, x * n) for n in range(2, 7)):
            return x
        x += 1
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
