import json
import time

# START - CODE GENERATED BY GPT
def solution():
    # Read the words from the file and split them
    with open('p042_words.txt', 'r') as f:
        words = f.read().replace('"', '').split(',')

    # Calculate the maximum possible word value
    max_value = 26 * 20  # 26 letters in the alphabet, longest word has 20 letters

    # Generate a list of triangle numbers up to the maximum possible value
    triangle_nums = set(int(0.5 * n * (n + 1)) for n in range(1, int((2 * max_value) ** 0.5) + 1))

    # Count the number of triangle words
    count = 0
    for word in words:
        value = sum(ord(c) - 64 for c in word)  # Calculate the word value
        if value in triangle_nums:  # Check if the value is a triangle number
            count += 1

    return count
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
