default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        exclude: .*solution\.py
        args: [ --fix ]
      - id: ruff-format
        exclude: .*solution\.py

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: .*solution\.py
        name: isort (python)
        args: ["--profile", "black"]

