import json
import time

# START - CODE GENERATED BY GPT
def solution():
    sum_of_squares = sum([i**2 for i in range(1, 101)])
    square_of_sum = sum(range(1, 101))**2
    return square_of_sum - sum_of_squares
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))