import json
import time

# START - CODE GENERATED BY GPT
def solution():
    def is_prime(n):
        if n < 2:
            return False
        for i in range(2, int(n**0.5)+1):
            if n % i == 0:
                return False
        return True

    prime_count = 0
    total_count = 1
    side_length = 1
    while True:
        side_length += 2
        for i in range(4):
            diagonal_num = side_length**2 - i*(side_length-1)
            if is_prime(diagonal_num):
                prime_count += 1
        total_count += 4
        if prime_count / total_count < 0.1:
            return side_length
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
