import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    max_length = 0
    max_num = 0
    for i in range(1, 1000000):
        n = i
        length = 1
        while n != 1:
            if n % 2 == 0:
                n = n // 2
            else:
                n = 3 * n + 1
            length += 1
        if length > max_length:
            max_length = length
            max_num = i
    return max_num
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
