import json
import time

# START - CODE GENERATED BY gpt4
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

def are_permutations(a, b, c):
    return sorted(str(a)) == sorted(str(b)) == sorted(str(c))

def solution():
    for a in range(1000, 10000):
        if is_prime(a):
            for b in range(a + 1, 10000):
                c = b + (b - a)
                if c < 10000 and is_prime(b) and is_prime(c) and are_permutations(a, b, c):
                    if a != 1487:  # Exclude the given sequence
                        return int(f"{a}{b}{c}")

# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
