import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    return sum(x for x in range(1000) if x % 3 == 0 or x % 5 == 0)
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
