import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    # Initialize variables
    product = 1
    current_length = 0
    target_positions = [1, 10, 100, 1000, 10000, 100000, 1000000]
    current_number = 1
    target_index = 0

    # Loop until we reach the last target position
    while target_index < len(target_positions):
        # Convert current number to string to iterate over its digits
        current_str = str(current_number)
        for digit in current_str:
            current_length += 1
            # Check if the current position is a target position
            if current_length == target_positions[target_index]:
                product *= int(digit)
                target_index += 1
                # Break if all target positions are found
                if target_index >= len(target_positions):
                    break
        current_number += 1

    return product
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
