import json
import time

# START - CODE GENERATED BY GPT
def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

def solution():
    n = 9
    while True:
        if not is_prime(n):
            found = False
            for i in range(1, int((n/2)**0.5)+1):
                if is_prime(n - 2*i*i):
                    found = True
                    break
            if not found:
                return n
        n += 2
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
