import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    from collections import defaultdict

    def digit_signature(n):
        return ''.join(sorted(str(n)))

    cubes = defaultdict(list)
    n = 1

    while True:
        cube = n ** 3
        signature = digit_signature(cube)
        cubes[signature].append(cube)

        if len(cubes[signature]) == 5:
            return min(cubes[signature])

        n += 1
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
