import json
import time

# START - CODE GENERATED BY GPT
def solution():
    num = 2**1000
    sum_of_digits = 0
    while num > 0:
        sum_of_digits += num % 10
        num //= 10
    return sum_of_digits
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))