import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def number_to_words(n):
        if n == 0:
            return ""
        elif n < 20:
            return ones[n]
        elif n < 100:
            return tens[n // 10] + ones[n % 10]
        elif n < 1000:
            return ones[n // 100] + "hundred" + ("and" + number_to_words(n % 100) if n % 100 != 0 else "")
        elif n == 1000:
            return "onethousand"

    ones = ["", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
            "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"]
    tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]

    total_letters = sum(len(number_to_words(i)) for i in range(1, 1001))
    return total_letters
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
