import json
import time

# START - CODE GENERATED BY GPT
def solution():
    # Define a dictionary to store the number of letters in each word
    num_dict = {
        1: 3, 2: 3, 3: 5, 4: 4, 5: 4, 6: 3, 7: 5, 8: 5, 9: 4, 10: 3,
        11: 6, 12: 6, 13: 8, 14: 8, 15: 7, 16: 7, 17: 9, 18: 8, 19: 8,
        20: 6, 30: 6, 40: 5, 50: 5, 60: 5, 70: 7, 80: 6, 90: 6
    }
    # Define a function to count the number of letters in a given number
    def count_letters(n):
        if n == 1000:
            return 11
        elif n >= 100:
            if n % 100 == 0:
                return num_dict[n // 100] + 7
            else:
                return num_dict[n // 100] + 10 + count_letters(n % 100)
        elif n >= 20:
            if n % 10 == 0:
                return num_dict[n]
            else:
                return num_dict[n // 10 * 10] + num_dict[n % 10]
        else:
            return num_dict[n]
    # Sum up the number of letters in all numbers from 1 to 1000
    total_letters = 0
    for i in range(1, 1001):
        total_letters += count_letters(i)
    return total_letters
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))