import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    pentagonals = set()
    for n in range(1, 10000):
        pentagonals.add(n * (3 * n - 1) // 2)
    min_d = float('inf')
    for j in pentagonals:
        for k in pentagonals:
            if j + k in pentagonals and k - j in pentagonals:
                d = abs(k - j)
                if d < min_d:
                    min_d = d
    return min_d
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))