import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def factorial(n):
        if n == 0 or n == 1:
            return 1
        result = 1
        for i in range(2, n + 1):
            result *= i
        return result

    # Precompute factorials of digits 0-9
    factorials = [factorial(i) for i in range(10)]

    # Upper bound: 7 * 9! = 2540160, because 8 * 9! is still a 7-digit number
    upper_bound = 7 * factorials[9]

    curious_sum = 0

    for number in range(10, upper_bound):
        digit_factorial_sum = sum(factorials[int(digit)] for digit in str(number))
        if digit_factorial_sum == number:
            curious_sum += number

    return curious_sum
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
