import json
import time

# START - CODE GENERATED BY GPT
def solution():
    # Using dynamic programming to solve the problem
    # Initializing the grid with 1's
    grid = [[1 for j in range(21)] for i in range(21)]
    # Filling the grid with the number of routes
    for i in range(1, 21):
        for j in range(1, 21):
            grid[i][j] = grid[i-1][j] + grid[i][j-1]
    # Returning the number of routes for a 20x20 grid
    return grid[20][20]
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))