import json
import time

# START - CODE GENERATED BY gpt3
import math
def solution():
    count = 0
    for n in range(1, 101):
        for r in range(1, n+1):
            if math.factorial(n)/(math.factorial(r)*math.factorial(n-r)) > 1000000:
                count += 1
    return count
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
