import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def binomial_coefficient(n, r):
        if r > n - r:
            r = n - r
        c = 1
        for i in range(r):
            c = c * (n - i) // (i + 1)
        return c

    count = 0
    for n in range(1, 101):
        for r in range(1, n + 1):
            if binomial_coefficient(n, r) > 1000000:
                count += 1
    return count
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
