import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    t, p, h = 285, 165, 143
    triangle, pentagonal, hexagonal = 40755, 40755, 40755
    while True:
        t += 1
        triangle = t * (t + 1) // 2
        while pentagonal < triangle:
            p += 1
            pentagonal = p * (3 * p - 1) // 2
        while hexagonal < triangle:
            h += 1
            hexagonal = h * (2 * h - 1)
        if triangle == pentagonal == hexagonal:
            return triangle
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))