import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def triangle_number(n):
        return n * (n + 1) // 2

    def pentagonal_number(n):
        return n * (3 * n - 1) // 2

    def hexagonal_number(n):
        return n * (2 * n - 1)

    # Start searching from the next number after the known solution
    n_t, n_p, n_h = 286, 166, 144

    while True:
        t = triangle_number(n_t)
        while pentagonal_number(n_p) < t:
            n_p += 1
        while hexagonal_number(n_h) < t:
            n_h += 1

        if t == pentagonal_number(n_p) == hexagonal_number(n_h):
            return t

        n_t += 1
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
