import json
import time

# START - CODE GENERATED BY GPT
def solution():
    n = 1001
    total = 1
    for i in range(3, n+1, 2):
        total += 4*(i**2) - 6*i + 6
    return total

# The solution is 669171001.
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))