import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    numerator_product = 1
    denominator_product = 1
    for numerator in range(10, 100):
        for denominator in range(numerator+1, 100):
            if numerator % 10 == 0 and denominator % 10 == 0:
                continue
            if numerator // 10 == denominator % 10 and numerator / denominator == (numerator % 10) / (denominator // 10):
                numerator_product *= numerator
                denominator_product *= denominator
            elif numerator % 10 == denominator // 10 and numerator / denominator == (numerator // 10) / (denominator % 10):
                numerator_product *= numerator
                denominator_product *= denominator
    for i in range(2, denominator_product+1):
        while numerator_product % i == 0 and denominator_product % i == 0:
            numerator_product //= i
            denominator_product //= i
    return denominator_product
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
