import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    from math import gcd

    def is_curious_fraction(numerator, denominator):
        num_str, den_str = str(numerator), str(denominator)
        if num_str[1] == '0' and den_str[1] == '0':
            return False
        for i in range(2):
            for j in range(2):
                if num_str[i] == den_str[j] and num_str[i] != '0':
                    new_num = int(num_str[1 - i])
                    new_den = int(den_str[1 - j])
                    if new_den != 0 and numerator * new_den == denominator * new_num:
                        return True
        return False

    product_num = 1
    product_den = 1

    for numerator in range(10, 100):
        for denominator in range(numerator + 1, 100):
            if is_curious_fraction(numerator, denominator):
                product_num *= numerator
                product_den *= denominator

    common_divisor = gcd(product_num, product_den)
    return product_den // common_divisor

# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
