import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    for a in range(1, 1000):
        for b in range(a+1, 1000):
            c = 1000 - a - b
            if a**2 + b**2 == c**2:
                return a*b*c
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
