import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    max_solutions = 0
    max_p = 0
    for p in range(12, 1001):
        num_solutions = 0
        for a in range(1, p//3):
            for b in range(a, (p-a)//2):
                c = p - a - b
                if c**2 == a**2 + b**2:
                    num_solutions += 1
        if num_solutions > max_solutions:
            max_solutions = num_solutions
            max_p = p
    return max_p
# The solution is 840.
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
