import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    max_solutions = 0
    best_p = 0

    for p in range(2, 1001, 2):
        solutions = 0
        for a in range(1, p // 3):
            if (p * (p - 2 * a)) % (2 * (p - a)) == 0:
                solutions += 1
        if solutions > max_solutions:
            max_solutions = solutions
            best_p = p

    return best_p
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
