import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def phi(n):
        result = n
        p = 2
        while p * p <= n:
            if n % p == 0:
                while n % p == 0:
                    n //= p
                result -= result // p
            p += 1
        if n > 1:
            result -= result // n
        return result

    limit = 1000000
    max_ratio = 0
    max_n = 0

    for n in range(2, limit + 1):
        phi_n = phi(n)
        ratio = n / phi_n
        if ratio > max_ratio:
            max_ratio = ratio
            max_n = n

    return max_n
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
