import json
import time

# START - CODE GENERATED BY GPT
def solution():
    limit = 1000000
    result = 1
    max_ratio = 0

    # Function to calculate Euler's Totient function
    def phi(n):
        result = n
        i = 2
        while i * i <= n:
            if n % i == 0:
                while n % i == 0:
                    n //= i
                result -= result // i
            i += 1
        if n > 1:
            result -= result // n
        return result

    for i in range(2, limit + 1):
        phi_val = phi(i)
        ratio = i / phi_val
        if ratio > max_ratio:
            max_ratio = ratio
            result = i

    return result
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
