import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    a, b = 1, 1
    index = 2
    while True:
        a, b = b, a + b
        index += 1
        if len(str(b)) >= 1000:
            return index
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
