import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def sum_of_divisors(n):
        total = 1
        for i in range(2, int(n**0.5) + 1):
            if n % i == 0:
                total += i
                if i != n // i:
                    total += n // i
        return total

    limit = 10000
    amicable_sum = 0
    for a in range(2, limit):
        b = sum_of_divisors(a)
        if b != a and b < limit and sum_of_divisors(b) == a:
            amicable_sum += a

    return amicable_sum
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
