import json
import time

# START - CODE GENERATED BY GPT
def solution():
    def d(n):
        return sum([i for i in range(1, n) if n % i == 0])

    amicable_sum = 0
    for a in range(1, 10000):
        b = d(a)
        if a != b and d(b) == a:
            amicable_sum += a
    return amicable_sum
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))