import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    a, b = 1, 2
    total = 0
    while b <= 4000000:
        if b % 2 == 0:
            total += b
        a, b = b, a + b
    return total
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
