import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    total = 0
    for i in range(1, 1001):
        total += i**i
    return total % 10**10

# The last ten digits of the series are: 9110846700
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))