import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def is_prime(num):
        if num < 2:
            return False
        if num in (2, 3):
            return True
        if num % 2 == 0 or num % 3 == 0:
            return False
        i = 5
        while i * i <= num:
            if num % i == 0 or num % (i + 2) == 0:
                return False
            i += 6
        return True

    max_primes = 0
    product_of_coefficients = 0

    for a in range(-999, 1000):
        for b in range(-1000, 1001):
            n = 0
            while True:
                quadratic_value = n * n + a * n + b
                if is_prime(quadratic_value):
                    n += 1
                else:
                    break
            if n > max_primes:
                max_primes = n
                product_of_coefficients = a * b

    return product_of_coefficients
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
