import json
import time

# START - CODE GENERATED BY GPT
import itertools
import sympy

def solution():
    primes = [3, 7, 109, 673] # start with the given primes
    for p in sympy.primerange(1000, 10000): # check primes between 1000 and 10000
        if all(sympy.isprime(int(str(p)+str(q))) and sympy.isprime(int(str(q)+str(p))) for q in primes):
            primes.append(p)
            if len(primes) == 5:
                return sum(primes)
    return None # if no set of 5 primes is found
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))