import json
import time

# START - CODE GENERATED BY GPT
def solution():
    num = 2520
    while True:
        divisible = True
        for i in range(11, 21):
            if num % i != 0:
                divisible = False
                break
        if divisible:
            return num
        num += 2520
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))