import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    # Calculate 100!
    factorial = 1
    for i in range(2, 101):
        factorial *= i

    # Calculate sum of digits in 100!
    digit_sum = 0
    for digit in str(factorial):
        digit_sum += int(digit)

    return digit_sum
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
