import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    def factorial(n):
        result = 1
        for i in range(2, n + 1):
            result *= i
        return result

    def sum_of_digits(number):
        return sum(int(digit) for digit in str(number))

    factorial_100 = factorial(100)
    return sum_of_digits(factorial_100)
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
