import json
import time

# START - CODE GENERATED BY gpt3
def solution():
    with open('p059_cipher.txt', 'r') as f:
        cipher = list(map(int, f.read().split(',')))
    for i in range(97, 123):
        for j in range(97, 123):
            for k in range(97, 123):
                key = [i, j, k]
                message = [cipher[n] ^ key[n % 3] for n in range(len(cipher))]
                text = ''.join([chr(m) for m in message])
                if ' the ' in text.lower():
                    return sum(message)
# END - CODE GENERATED BY gpt3

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
