import json
import time

# START - CODE GENERATED BY gpt4
def is_palindrome(s):
    return s == s[::-1]

def solution():
    total_sum = 0
    for number in range(1, 1000000):
        decimal_str = str(number)
        binary_str = bin(number)[2:]
        if is_palindrome(decimal_str) and is_palindrome(binary_str):
            total_sum += number
    return total_sum
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
