import json
import time

# START - CODE GENERATED BY GPT
def solution():
    i = 1
    while True:
        triangle_num = i*(i+1)//2
        divisors = 0
        for j in range(1, int(triangle_num**0.5)+1):
            if triangle_num % j == 0:
                divisors += 2
        if divisors > 500:
            return triangle_num
        i += 1
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
