import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    target_numerator = 3
    target_denominator = 7
    max_denominator = 1000000

    closest_numerator = 0
    closest_denominator = 1

    for d in range(2, max_denominator + 1):
        n = (target_numerator * d - 1) // target_denominator
        if n * closest_denominator > closest_numerator * d:
            closest_numerator = n
            closest_denominator = d

    return closest_numerator
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
