import json
import time

# START - CODE GENERATED BY gpt4
def solution():
    count = 0
    n = 1
    while True:
        found = False
        base = 1
        while True:
            power = base ** n
            length = len(str(power))
            if length == n:
                count += 1
                found = True
            elif length > n:
                break
            base += 1
        if not found:
            break
        n += 1
    return count
# END - CODE GENERATED BY gpt4

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))
