import json
import time

# START - CODE GENERATED BY GPT
def solution():
    count = 0
    for i in range(1, 10):
        for j in range(1, 22):
            if len(str(i**j)) == j:
                count += 1
    return count
# END - CODE GENERATED BY GPT

cpu_s, wall_s = time.process_time(), time.time()
result = solution()
cpu_e, wall_e = time.process_time(), time.time()

cpu_time, wall_time = cpu_e - cpu_s, wall_e - wall_s
print(json.dumps({"solution": result, "cpu": cpu_time, "wall": wall_time}))